import * as path from "node:path";
import type { BddFeature, BddScenario, Requirement, SpecDocument } from "../types.js";
import { writeText } from "../util.js";

const GENERAL = "general";

function capabilityOf(req: Requirement): string {
  return req.capability ?? GENERAL;
}

/** Turn a requirement into a single, traceable Gherkin scenario. */
function scenarioFromRequirement(req: Requirement, capability: string): BddScenario {
  const outcome = req.text.replace(/\s+/g, " ").trim();
  const action =
    req.kind === "functional"
      ? `I exercise the ${capability} capability`
      : `I evaluate the ${capability} ${req.kind === "non-functional" ? "quality attribute" : "constraint"}`;

  return {
    name: `${req.id} — ${truncate(outcome)}`,
    tags: [`@${req.id}`, `@${capability}`, `@${req.kind}`],
    given: ["the tokenizer application is loaded"],
    when: [action],
    then: [`the system satisfies "${outcome}"`],
    requirementId: req.id,
  };
}

/** Generate one BDD feature per capability, with a scenario per requirement. */
export function generateFeatures(spec: SpecDocument): BddFeature[] {
  const byCapability = new Map<string, Requirement[]>();
  for (const req of spec.requirements) {
    const cap = capabilityOf(req);
    if (!byCapability.has(cap)) byCapability.set(cap, []);
    byCapability.get(cap)!.push(req);
  }

  const features: BddFeature[] = [];
  for (const [capability, requirements] of byCapability) {
    const story = spec.userStories.find((s) => s.want.toLowerCase().includes(capability)) ?? spec.userStories[0];
    features.push({
      capability,
      title: `${spec.title} — ${capability}`,
      narrative: story
        ? { role: story.role, want: story.want, soThat: story.soThat }
        : { role: "user", want: `to use ${capability}`, soThat: "the feature delivers its specified value" },
      scenarios: requirements.map((r) => scenarioFromRequirement(r, capability)),
      requirementIds: requirements.map((r) => r.id),
    });
  }

  return features.sort((a, b) => a.capability.localeCompare(b.capability));
}

export function renderFeature(feature: BddFeature): string {
  const scenarios = feature.scenarios
    .map((s) => {
      const steps = [
        ...s.given.map((g) => `    Given ${g}`),
        ...s.when.map((w) => `    When ${w}`),
        ...s.then.map((t) => `    Then ${t}`),
      ].join("\n");
      return `  ${s.tags.join(" ")}\n  Scenario: ${s.name}\n${steps}`;
    })
    .join("\n\n");

  return `# Generated by @tokenizer/sdlc — grounded in: ${feature.requirementIds.join(", ")}
@${feature.capability}
Feature: ${feature.title}
  As a ${feature.narrative.role}
  I want ${feature.narrative.want}
  So that ${feature.narrative.soThat}

${scenarios}
`;
}

export async function writeFeatures(dir: string, features: BddFeature[]): Promise<string[]> {
  const files: string[] = [];
  for (const feature of features) {
    const file = path.join(dir, `${feature.capability}.feature`);
    await writeText(file, renderFeature(feature));
    files.push(file);
  }
  return files;
}

function truncate(text: string, max = 70): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}
