# Generated by @tokenizer/sdlc — grounded in: FR-004, FR-006, FR-008, FR-009, CON-002
@comparison
Feature: Model Cost Comparison Panel — comparison
  As a Copilot user
  I want to compare the input cost of my text across models
  So that I can choose the cheapest model that still fits my prompt

  @FR-004 @comparison @functional
  Scenario: FR-004 — The UI MUST display a comparison table with one row per model, showin…
    Given the tokenizer application is loaded
    When I exercise the comparison capability
    Then the system satisfies "The UI MUST display a comparison table with one row per model, showing name, provider, input cost (USD and credits), and context-window usage."

  @FR-006 @comparison @functional
  Scenario: FR-006 — The comparison table MUST be sortable by input cost and by context us…
    Given the tokenizer application is loaded
    When I exercise the comparison capability
    Then the system satisfies "The comparison table MUST be sortable by input cost and by context usage."

  @FR-008 @comparison @functional
  Scenario: FR-008 — The panel MUST update responsively as the user edits the input.
    Given the tokenizer application is loaded
    When I exercise the comparison capability
    Then the system satisfies "The panel MUST update responsively as the user edits the input."

  @FR-009 @comparison @functional
  Scenario: FR-009 — The system MUST handle the model set shown by default [NEEDS CLARIFIC…
    Given the tokenizer application is loaded
    When I exercise the comparison capability
    Then the system satisfies "The system MUST handle the model set shown by default [NEEDS CLARIFICATION: show all models, only GA models, or only the user's recent models?]."

  @CON-002 @comparison @constraint
  Scenario: CON-002 — No new runtime dependencies may be added for this feature.
    Given the tokenizer application is loaded
    When I evaluate the comparison constraint
    Then the system satisfies "No new runtime dependencies may be added for this feature."
