# Generated by @tokenizer/sdlc — grounded in: FR-002, FR-003, NFR-002, CON-001
@cost-estimation
Feature: Model Cost Comparison Panel — cost-estimation
  As a Copilot user
  I want to compare the input cost of my text across models
  So that I can choose the cheapest model that still fits my prompt

  @FR-002 @cost-estimation @functional
  Scenario: FR-002 — The system MUST compute the estimated input cost in USD for every mod…
    Given the tokenizer application is loaded
    When I exercise the cost-estimation capability
    Then the system satisfies "The system MUST compute the estimated input cost in USD for every model in `COPILOT_MODEL_OPTIONS`."

  @FR-003 @cost-estimation @functional
  Scenario: FR-003 — The system MUST also express each cost in AI credits using the docume…
    Given the tokenizer application is loaded
    When I exercise the cost-estimation capability
    Then the system satisfies "The system MUST also express each cost in AI credits using the documented 1 credit = $0.01 conversion."

  @NFR-002 @cost-estimation @non-functional
  Scenario: NFR-002 — Recomputing the full comparison after an input change MUST complete i…
    Given the tokenizer application is loaded
    When I evaluate the cost-estimation quality attribute
    Then the system satisfies "Recomputing the full comparison after an input change MUST complete in under 50 ms for inputs up to 10,000 tokens."

  @CON-001 @cost-estimation @constraint
  Scenario: CON-001 — All currency math MUST reuse `copilotModels.ts` helpers; no duplicate…
    Given the tokenizer application is loaded
    When I evaluate the cost-estimation constraint
    Then the system satisfies "All currency math MUST reuse `copilotModels.ts` helpers; no duplicated pricing constants."
