# Generated by @tokenizer/sdlc — grounded in: FR-007
@persistence
Feature: Model Cost Comparison Panel — persistence
  As a Copilot user
  I want to compare the input cost of my text across models
  So that I can choose the cheapest model that still fits my prompt

  @FR-007 @persistence @functional
  Scenario: FR-007 — The system SHOULD persist the user's selected subset of models to loc…
    Given the tokenizer application is loaded
    When I exercise the persistence capability
    Then the system satisfies "The system SHOULD persist the user's selected subset of models to local storage and restore it on reload."
