# Generated by @tokenizer/sdlc — grounded in: FR-001
@tokenization
Feature: Model Cost Comparison Panel — tokenization
  As a Copilot user
  I want to compare the input cost of my text across models
  So that I can choose the cheapest model that still fits my prompt

  @FR-001 @tokenization @functional
  Scenario: FR-001 — The system MUST tokenize the current input text using the existing `t…
    Given the tokenizer application is loaded
    When I exercise the tokenization capability
    Then the system satisfies "The system MUST tokenize the current input text using the existing `tokenize` function."
