# Generated by @tokenizer/sdlc — grounded in: FR-005, NFR-001
@visualization
Feature: Model Cost Comparison Panel — visualization
  As a Copilot user
  I want to compare the input cost of my text across models
  So that I can choose the cheapest model that still fits my prompt

  @FR-005 @visualization @functional
  Scenario: FR-005 — The UI MUST visually highlight any model whose context window cannot …
    Given the tokenizer application is loaded
    When I exercise the visualization capability
    Then the system satisfies "The UI MUST visually highlight any model whose context window cannot fit the current token count."

  @NFR-001 @visualization @non-functional
  Scenario: NFR-001 — The panel MUST meet WCAG 2.1 AA — the table MUST use semantic table m…
    Given the tokenizer application is loaded
    When I evaluate the visualization quality attribute
    Then the system satisfies "The panel MUST meet WCAG 2.1 AA — the table MUST use semantic table markup with a header row, and all highlight states MUST have a non-color affordance and a contrast ratio of at least 4.5:1."
