# Generated by @tokenizer/sdlc — grounded in: FR-001, FR-008, NFR-003
@canvas-integration
Feature: Tokenizer Copilot Desktop Canvas — canvas-integration
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-001 @canvas-integration @functional
  Scenario: FR-001 — The system MUST register a GitHub Copilot desktop canvas extension at…
    Given the tokenizer application is loaded
    When I exercise the canvas-integration capability
    Then the system satisfies "The system MUST register a GitHub Copilot desktop canvas extension at `.github/extensions/tokenizer/extension.mjs` that declares a canvas (via `createCanvas`/`joinSession`) discoverable in the app's side panel and serves its UI from a per-instance loopback HTTP server."

  @FR-008 @canvas-integration @functional
  Scenario: FR-008 — The canvas MUST expose agent/host-callable canvas actions — at minimu…
    Given the tokenizer application is loaded
    When I exercise the canvas-integration capability
    Then the system satisfies "The canvas MUST expose agent/host-callable canvas actions — at minimum `set_text` (load text into the canvas) and `get_summary` (return the current metrics) — through the canvas SDK action contract."

  @NFR-003 @canvas-integration @non-functional
  Scenario: NFR-003 — The extension MUST NOT write to `stdout` (reserved for JSON-RPC); all…
    Given the tokenizer application is loaded
    When I evaluate the canvas-integration quality attribute
    Then the system satisfies "The extension MUST NOT write to `stdout` (reserved for JSON-RPC); all user-visible logging MUST go through `session.log`, and the embedded HTTP server MUST bind to loopback (`127.0.0.1`) only."
