# Generated by @tokenizer/sdlc — grounded in: FR-006
@comparison
Feature: Tokenizer Copilot Desktop Canvas — comparison
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-006 @comparison @functional
  Scenario: FR-006 — The canvas MUST present a comparison table with one row per model sho…
    Given the tokenizer application is loaded
    When I exercise the comparison capability
    Then the system satisfies "The canvas MUST present a comparison table with one row per model showing name, provider, input cost (USD and credits), and context-window usage, and the table MUST be sortable by input cost and by context usage."
