# Generated by @tokenizer/sdlc — grounded in: FR-005
@cost-estimation
Feature: Tokenizer Copilot Desktop Canvas — cost-estimation
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-005 @cost-estimation @functional
  Scenario: FR-005 — The system MUST compute the estimated input cost in USD and in AI cre…
    Given the tokenizer application is loaded
    When I exercise the cost-estimation capability
    Then the system satisfies "The system MUST compute the estimated input cost in USD and in AI credits (using the documented 1 credit = $0.01 conversion) for every model in `COPILOT_MODEL_OPTIONS`."
