# Generated by @tokenizer/sdlc — grounded in: FR-010, NFR-002
@interaction
Feature: Tokenizer Copilot Desktop Canvas — interaction
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-010 @interaction @functional
  Scenario: FR-010 — The canvas MUST recompute and update all derived views (tokens, summa…
    Given the tokenizer application is loaded
    When I exercise the interaction capability
    Then the system satisfies "The canvas MUST recompute and update all derived views (tokens, summary metrics, comparison table) responsively as the user edits the input."

  @NFR-002 @interaction @non-functional
  Scenario: NFR-002 — Recomputing the full set of derived views after an input change MUST …
    Given the tokenizer application is loaded
    When I evaluate the interaction quality attribute
    Then the system satisfies "Recomputing the full set of derived views after an input change MUST complete in under 50 ms for inputs up to 10,000 tokens."
