# Generated by @tokenizer/sdlc — grounded in: FR-009
@persistence
Feature: Tokenizer Copilot Desktop Canvas — persistence
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-009 @persistence @functional
  Scenario: FR-009 — The system MUST persist the user's latest input text **scoped to the …
    Given the tokenizer application is loaded
    When I exercise the persistence capability
    Then the system satisfies "The system MUST persist the user's latest input text **scoped to the Copilot session** (keyed by `sessionId`) and restore it when the canvas is reopened within that same session. Persistence MUST write to the extension's own session-scoped artifacts directory under `$COPILOT_HOME` (deliberately outside the repository working tree); reopening the canvas in a different session MUST NOT surface another session's text. See ADR-002 / MSF-006."
