# Generated by @tokenizer/sdlc — grounded in: FR-002
@tokenization
Feature: Tokenizer Copilot Desktop Canvas — tokenization
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-002 @tokenization @functional
  Scenario: FR-002 — The canvas MUST tokenize the current input text using the project's e…
    Given the tokenizer application is loaded
    When I exercise the tokenization capability
    Then the system satisfies "The canvas MUST tokenize the current input text using the project's existing `tokenize` algorithm, ported faithfully to the extension runtime so token boundaries match `src/lib/tokenizer.ts`."
