# Generated by @tokenizer/sdlc — grounded in: FR-003, FR-004, FR-007, NFR-001
@visualization
Feature: Tokenizer Copilot Desktop Canvas — visualization
  As a Copilot desktop user
  I want to open the tokenizer in the side panel
  So that I can inspect tokenization of my prompt while I keep working in chat

  @FR-003 @visualization @functional
  Scenario: FR-003 — The canvas MUST display summary metrics for the current input: charac…
    Given the tokenizer application is loaded
    When I exercise the visualization capability
    Then the system satisfies "The canvas MUST display summary metrics for the current input: characters, bytes, words, lines, and token count."

  @FR-004 @visualization @functional
  Scenario: FR-004 — The canvas MUST render each token as a discrete, labeled segment and …
    Given the tokenizer application is loaded
    When I exercise the visualization capability
    Then the system satisfies "The canvas MUST render each token as a discrete, labeled segment and MUST distinguish token categories using both color and a non-color affordance (visible category label or pattern)."

  @FR-007 @visualization @functional
  Scenario: FR-007 — The canvas MUST visually highlight any model whose context window can…
    Given the tokenizer application is loaded
    When I exercise the visualization capability
    Then the system satisfies "The canvas MUST visually highlight any model whose context window cannot fit the current token count, with a non-color affordance in addition to color."

  @NFR-001 @visualization @non-functional
  Scenario: NFR-001 — The canvas MUST meet WCAG 2.1 AA — the comparison table MUST use sema…
    Given the tokenizer application is loaded
    When I evaluate the visualization quality attribute
    Then the system satisfies "The canvas MUST meet WCAG 2.1 AA — the comparison table MUST use semantic table markup with a header row, every highlight/over-limit state MUST carry a non-color affordance, and all text MUST have a contrast ratio of at least 4.5:1. The canvas MUST style with the host-provided canvas theme tokens (e.g. `--background-color-default`, `--text-color-default`, `--font-sans`, `--font-mono`) so it matches the app's light/dark themes."
